dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x mvnw
services:
- postgresql
addons:
  postgresql: '9.6'
cache:
  directories:
  - "$HOME/.m2"
before_script:
- psql -c 'create user "ese2017-full-integration" password '"'"'ese2017-full-integration'"'"'
  createdb;' -U postgres
- psql -c 'create database "ese2017-full-integration"' -U ese2017-full-integration
  postgres
deploy:
  provider: heroku
  app: eseteam6
  api_key:
    secure: k9NPwaK1hhi7KNp+RgHga4PlSvtN/jwGjia4mJNoarRMaN2uobXNoWw2hUBFa/RP2jgTJrTKgOuv7cYijHsJBSJP43DzV1ZmcX0YB4Wgc10yKhDP7Kch0TjQI21IyAdKRQLTaLbh6m5/hX2jg2l9VO5ss29gKL/uFilhATeWGykI9j2SrS1Er03GzAH0Toa3gjjByowkSZABiCjSiBKmNmpsiOjX826xpO/6rIpYhwCMsDhGyKkRlb0bGk9LiJ1UGzRH3/JJx10DubTjrNkZDirSZX+HyASz6S9WtmEp9gSqdC6mmIbBTOuaDDd+ifksFkOLaz3cC9mQa2TwS6Yy6DvG+eKAwnNwg3yNkn/TR+EwTmxl4FzoYiNIKx9bsBaOd8cp60WFWR/XDT/c51sVXIVvHwBqusEUaa8YC/m/XCEuUrndyI/rlPHINhVLttiX9inwPVR4K8Mp4VV+mkD55lk/1LD9eiYxbCeiY0/d4WNmBj/AvegWWFIE1iCaKfQ7XAx1Q5apqM4p7RgPmo0aKP7igCtZzUlJ6iwurRINx4nKuZiUX9avCAj/bOY8oW5YG0iVssqn4HcJSMndyoceJoGK5n+n+mf4buIu2rN5YvVOT/soECTlJzC15Q8Te+pKNZAlXRZtXUg9ZEZuqfXI8Fh1ZMqJ+sYxbN/uic7WJfo=

