dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x mvnw
services:
- postgresql
addons:
  postgresql: '9.6'
cache:
  directories:
  - "$HOME/.m2"
before_script:
- psql -c 'create user "ese2017-full-integration" password '"'"'ese2017-full-integration'"'"'
  createdb;' -U postgres
- psql -c 'create database "ese2017-full-integration"' -U ese2017-full-integration
  postgres
deploy:
  provider: heroku
  app: eseteam6
  api_key:
    secure: Wp/0ksN55sXVTgDv+H/mMcuu74mglWF9h/wB49WtfZCupmPpfi6+jLDIXEu9oPUP0CigVLNNI/CiCi9jcPuTop5cwUQPTWPnzFG1aEotirt/VjuJ+j1YkwRBeVCRAkzJkIAfvT7sRzvBb+hR0U0w+TjqNy4XpqTgwOxEcAH/zefVWwAUM2GelyuE2JLhMl6Stswksae1tHOIP7tANOaf2auKlkS3NCJ95n4/qMdIrEOlLPUAqZV7twtz1NKUPABRJgILTxBKFkYm0qUcR33mv8OdpHy4gMfl8tLwuabh8mFUHxOyFW0vT5EeHZPZvKVWgXSrmEz1GDWdrL0KvCLmqValzYTBOwC8ZreE+bjlGREqi5R31X3Vk2BcKtN8ZpaHXOZ7JCGT5EfcjCcfJY/5Ek+OfcYDtM9NoCgKdErFnQdVuW+f65xFyPXDDJUAEiKIUEVJtvw7p3K76Fe97/yFUYC9AZBTiQTobzIXeqX3RiiIDTir978r0YABc7rgDeq9mpkpiqn6ZL1tcCKM5kfTWeg91gegIT112MSa/rFjbrt06I5B1P48Pdt9GBVyoS/BrjsFf1x7aiJUri4v6o/wG34fR4IIGgIwL6prybxXAve21YMT4vFOFt2QlbRAI5fKLW9n7xsgM1c0R3qU7VgJfErdByISZPKyLnK8CdXchK4=
